{% set name = "blinker" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/blinker-{{ version }}.tar.gz
  sha256: b4ce2265a7abece45e7cc896e98dbebe6cead56bcf805a3d23136d145f5445bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core <4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - blinker
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pallets-eco/blinker
  license: MIT
  license_file: LICENSE.txt
  summary: Fast, simple object-to-object and broadcast signaling

extra:
  recipe-maintainers:
    - ocefpaf
    - frol
    - synapticarbors
